#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/sbin/tumgrd
CONFIGNAME="tumgrd"

start_service() {
	local enabled database interval log_level enable_xor

	config_load "$CONFIGNAME"
	config_get enabled main enabled '1'
	[ "$enabled" = "1" ] || return 0

	config_get database main database '/lib/tumgrd/tumgrd.db'
	config_get interval main interval '300'
	config_get log_level main log_level 'info'
	config_get enable_xor main enable_xor '0'

	args="-d $database -i $interval"
	if [ "$enable_xor" = "1" ]; then
		args="$args --enable-xor"
	fi
	args="$args --log-level $log_level"

	procd_open_instance
	procd_set_param command "$PROG" $args
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
